import { Subscription, SpendTrend } from "./types";

export const mockSubscriptions: Subscription[] = [
  {
    id: "1",
    platform: "ChatGPT",
    icon: "Bot",
    amount: 20,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-01-15",
    billing_day: 15,
    status: "active",
    plan_type: "premium",
    payment_source: "Company Capital Card",
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    platform: "n8n",
    icon: "Workflow",
    amount: 24,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-02-06",
    billing_day: 6,
    status: "active",
    plan_type: "premium",
    payment_source: "Company Capital Card",
    created_at: "2024-02-06T00:00:00Z",
  },
  {
    id: "3",
    platform: "Vapi",
    icon: "Phone",
    amount: 50,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-03-01",
    billing_day: 1,
    status: "active",
    plan_type: "premium",
    payment_source: "Founder Personal Card",
    created_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "4",
    platform: "Twilio",
    icon: "MessageSquare",
    amount: 35,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-01-20",
    billing_day: 20,
    status: "active",
    plan_type: "basic",
    payment_source: "Company Capital Card",
    created_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "5",
    platform: "Vercel",
    icon: "Globe",
    amount: 20,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-04-10",
    billing_day: 10,
    status: "active",
    plan_type: "premium",
    payment_source: "Company Capital Card",
    created_at: "2024-04-10T00:00:00Z",
  },
  {
    id: "6",
    platform: "Notion",
    icon: "FileText",
    amount: 8,
    currency: "GBP",
    billing_cycle: "monthly",
    subscription_date: "2024-02-12",
    billing_day: 12,
    status: "active",
    plan_type: "premium",
    payment_source: "Founder Personal Card",
    created_at: "2024-02-12T00:00:00Z",
  },
  {
    id: "7",
    platform: "Anthropic",
    icon: "Brain",
    amount: 60,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-05-01",
    billing_day: 1,
    status: "active",
    plan_type: "premium",
    payment_source: "Company Capital Card",
    created_at: "2024-05-01T00:00:00Z",
  },
  {
    id: "8",
    platform: "Figma",
    icon: "Palette",
    amount: 15,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-03-22",
    billing_day: 22,
    status: "canceled",
    plan_type: "trial_finished",
    payment_source: "Company Capital Card",
    created_at: "2024-03-22T00:00:00Z",
  },
  {
    id: "9",
    platform: "Supabase",
    icon: "Database",
    amount: 25,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-06-05",
    billing_day: 5,
    status: "active",
    plan_type: "premium",
    payment_source: "Company Capital Card",
    created_at: "2024-06-05T00:00:00Z",
  },
  {
    id: "10",
    platform: "Midjourney",
    icon: "Image",
    amount: 10,
    currency: "USD",
    billing_cycle: "monthly",
    subscription_date: "2024-07-01",
    billing_day: 1,
    status: "active",
    plan_type: "trial",
    payment_source: "Founder Personal Card",
    created_at: "2024-07-01T00:00:00Z",
  },
];

export const mockSpendTrend: SpendTrend[] = [
  { month: "Oct", amount: 180 },
  { month: "Nov", amount: 210 },
  { month: "Dec", amount: 195 },
  { month: "Jan", amount: 245 },
  { month: "Feb", amount: 267 },
  { month: "Mar", amount: 290 },
];
